<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * audit_log - every edit/access/admin action. Append-only, partitioned by month like
 * scan_events. Satisfies the regulatory audit-trail obligation and admin impersonation logging.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE audit_log (
                id              bigint GENERATED BY DEFAULT AS IDENTITY,
                organization_id uuid,
                actor_id        uuid,
                action          text NOT NULL,
                target          text,
                meta            jsonb,
                ts              timestamptz NOT NULL DEFAULT now(),
                PRIMARY KEY (id, ts)
            ) PARTITION BY RANGE (ts);
        SQL);

        DB::statement('CREATE INDEX audit_log_org_ts ON audit_log (organization_id, ts DESC)');
        DB::statement('CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT');

        $start = Carbon::create(2026, 6, 1);
        for ($i = 0; $i < 3; $i++) {
            $from = $start->copy()->addMonths($i);
            $to = $from->copy()->addMonth();
            $name = 'audit_log_' . $from->format('Y_m');
            DB::statement(sprintf(
                "CREATE TABLE %s PARTITION OF audit_log FOR VALUES FROM ('%s') TO ('%s')",
                $name, $from->format('Y-m-d'), $to->format('Y-m-d')
            ));
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_log');
    }
};
