<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * scan_events - the largest, fastest-growing table. Partitioned by month so passport
 * lookups never touch this volume and old partitions can be archived/dropped cheaply.
 *
 * GDPR: ip_hash is a KEYED HMAC (rotating salt via SCAN_IP_HMAC_KEY), not a bare hash.
 *
 * Partition maintenance (creating next month's partition ahead of the boundary) is a
 * scheduled command - see App\Console\Commands\EnsurePartitions. We pre-create a few here.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Partition key (ts) must be part of the primary key in Postgres.
        DB::statement(<<<'SQL'
            CREATE TABLE scan_events (
                id          bigint GENERATED BY DEFAULT AS IDENTITY,
                passport_id uuid NOT NULL,
                ts          timestamptz NOT NULL DEFAULT now(),
                link_type   text,
                locale      text,
                country     text,
                ua_class    text,
                ip_hash     text,
                PRIMARY KEY (id, ts)
            ) PARTITION BY RANGE (ts);
        SQL);

        DB::statement('CREATE INDEX scan_events_passport_ts ON scan_events (passport_id, ts DESC)');

        // DEFAULT partition catches anything outside explicit ranges (insert never fails).
        DB::statement('CREATE TABLE scan_events_default PARTITION OF scan_events DEFAULT');

        // Pre-create this month + next two months.
        $start = Carbon::create(2026, 6, 1);
        for ($i = 0; $i < 3; $i++) {
            $from = $start->copy()->addMonths($i);
            $to = $from->copy()->addMonth();
            $name = 'scan_events_'.$from->format('Y_m');
            DB::statement(sprintf(
                "CREATE TABLE %s PARTITION OF scan_events FOR VALUES FROM ('%s') TO ('%s')",
                $name, $from->format('Y-m-d'), $to->format('Y-m-d')
            ));
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('scan_events');   // drops all partitions
    }
};
