<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Append-only platform audit trail (regulatory obligation + admin impersonation logging).
 * The table's primary key is (id, ts) only because Postgres range-partitioning requires the
 * partition key in the PK -- `id` is still a true GENERATED BY DEFAULT AS IDENTITY surrogate
 * column, and rows here are only ever inserted, never updated/fresh()/refresh()d. Unlike
 * PublishedSnapshot (which has no surrogate key at all and IS updated), Eloquent's default
 * single-column `id` key handling is correct here -- no setKeysForSaveQuery() override needed.
 */
class AuditLog extends Model
{
    protected $table = 'audit_log';

    public $timestamps = false; // 'ts' has its own DB-side default now(), not created_at/updated_at

    protected $fillable = ['organization_id', 'actor_id', 'action', 'target', 'meta'];

    protected $casts = [
        'meta' => 'array',
        'ts' => 'datetime',
    ];

    public static function record(
        string $action,
        ?string $target = null,
        array $meta = [],
        ?string $actorId = null,
        ?string $organizationId = null,
    ): self {
        return static::create([
            'actor_id' => $actorId ?? Auth::id(),
            'organization_id' => $organizationId ?? (app()->bound('currentOrganizationId') ? app('currentOrganizationId') : null),
            'action' => $action,
            'target' => $target,
            'meta' => $meta,
        ]);
    }
}
